### PR TITLE
Add a docker file.

### PR DESCRIPTION
**Pull request by peterj**
Fixe #7

### CODE REVIEW

**Comment by joshghent** [comment]
@peterj Awesome! Thank you for this, looks fantastic. Have you been able to test the docker build out?

**Comment by peterj** [comment]
The image builds, I wasn't able to try it out though - will do today with that config change.

**Comment by peterj** [comment]
@joshghent it builds and runs; I also updated the README and added a .dockerignore file so the .env file doesn't get copied to the image. I tried to test this on Discord as well, but didn't get too far with it as I am not familiar with it :)

**Comment by joshghent** [comment]
@peterj Apologies for not seeing this! Looks great! Thank you very much for your kind contribution 🎉

**Pull request merged**
